### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dvskabangira** [nadhiranoor/Lightweight-MixVPR#1]
Thanks for the great work!
I would like to know whether you are intending to release code for this paper you implemented>>"A Lightweight Skeleton-Based 3D-CNN for Real-Time Fall Detection and
Action Recognition
Thanks in advance

**Comment by nadhiranoor** [comment]
Hello, thank you for the appreciation.
Unfortunately, this work is a collaboration with a company, therefore, I
can't make it public since its their property.

Best regards,

*Nadhira Noor*

Phone :+62-878-8445-1662 <%2B62-812-8763-5179>
Email : ***@***.*** ***@***.***>
           ***@***.*** ***@***.***>

**Comment by dvskabangira** [comment]
I understand!
Thanks for kind and quick response!
